export const words = [
  { word: "cooper", hint: "The former NASA pilot turned farmer." },
  { word: "murphy", hint: "The daughter who stays on Earth to solve the gravity equation." },
  { word: "tars", hint: "A witty, rectangular robot with adjustable personality settings." },
  { word: "gargantua", hint: "The massive, spinning black hole in the film." },
  { word: "endurance", hint: "The circular mothership that rotates to create gravity." },
  { word: "wormhole", hint: "A 'shortcut' through space found near Saturn." },
  { word: "tesseract", hint: "The 5-dimensional 'room' inside the black hole." },
  { word: "docking", hint: "The most famous, high-stress maneuver in the movie." },
  { word: "miller", hint: "The name of the first planet the crew visits (the water planet)." },
  { word: "blight", hint: "The global crop disease that is killing Earth." },
  { word: "morse", hint: "The code used to send messages through a watch." },
  { word: "stay", hint: "The four-letter word Cooper sends to himself from the future." },
  { word: "lazarus", hint: "The name of the initial missions where 12 scientists were sent out." },
  { word: "case", hint: "The other robot teammate who helps Brand on the water planet." },
  { word: "gravity", hint: "The force that Murphy is trying to 'solve' to save humanity." },
  { word: "corn", hint: "The last remaining crop on Earth before the film starts." },
  { word: "watch", hint: "The item Cooper gives Murphy to 'sync' their time." },
  { word: "brand", hint: "The female scientist played by Anne Hathaway." },
  { word: "ranger", hint: "The smaller landing craft used to go down to planets." },
  { word: "ghost", hint: "What Murphy calls the entity knocking books off her shelf." },
  { word: "mann", hint: "The scientist found on the ice planet who betrays the crew." },
  { word: "planet", hint: "The crew is looking for a new one to call home." },
  { word: "galaxy", hint: "A massive system of stars, gas, and dust." },
  { word: "orbit", hint: "The curved path a spacecraft takes around a planet." },
  { word: "vacuum", hint: "The state of space where there is no air or pressure." },
  { word: "rocket", hint: "The engine or vehicle used to launch things into space." },
  { word: "comet", hint: "A 'dirty snowball' made of ice and dust with a long tail." },
  { word: "astronaut", hint: "A person trained to travel in a spacecraft." },
  { word: "nebula", hint: "A giant cloud of dust and gas in space." },
  { word: "saturn", hint: "The sixth planet from the sun with famous rings." }
];